### ISSUE TITLE
Metadata with keys starting with org_ 

### ISSUE THREAD

**Issue by chStaiger** [iBridges-for-iRODS/iBridges#259]
To be compatible with Yoda servers we do not show metadata entries with keys starting with `org_`. However, one can create such metadata entries with iBridges, which then in turn are not listed in the `meta` object.

@qubixes  What shall we do about that? 
I am not in favour of "blacklisting" keys, since that should happen on the iRODS server. But for now I would suggest to also throw at least a warning when someone creates such a blacklisted metadata item to be consistent in our software package. To be very consistent we can also throw an Exception "NotAllowed" ...

**Comment by qubixes** [comment]
I don't think there are good solutions here on our side. I think throwing an exception will be the most consistent way indeed.

**Comment by trel** [comment]
How does a Yoda system handle iCommands being able to create keys starting with `_org`?  Whatever the server policy, it should be client agnostic (or specific, if whitelisting)...

**Comment by chStaiger** [comment]
With the icommands you can create such metadata as a user. We excluded listing metadata with keys starting with "org_" since the Yoda system uses those keys to trigger certain behaviour on the server like replication. So it is not save for users to mingle with those metadata. 
I think in a later version those keys will be protected by the Yoda system, but for now, we had to implement that into iBridges for our upload and download including metadata.

https://github.com/UtrechtUniversity/yoda/discussions/434

**Comment by trel** [comment]
Makes sense.

Server should protect those (perhaps with https://github.com/irods/irods_rule_engine_plugin_metadata_guard/).
