### ISSUE TITLE
Multi threading data retrieval

### ISSUE THREAD

**Issue by jjkoehorst** [iBridges-for-iRODS/iBridges#282]
![image](https://github.com/user-attachments/assets/8cacb1a9-e619-40a7-bac2-178d24320f33)

i think the tqdm library gives these fancy progress bars but does not clear them up nicely in multi threading mode so it clogs up the entire progress (log section).

**Comment by chStaiger** [comment]
@jjkoehorst I think we cannot do much to make the progress bar work flawlessly for multi threaded uploads. But you can switch off the progressbars when working with several threads like this:

```
import os
os.environ["TQDM_DISABLE"] = "1"
```
